spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/OurLibrary
    username: postgres
    password: matias1234
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres